# packages in environment at /Users/tobijohn/tensorflow-test/env:
#
# Name                    Version                   Build  Channel
abseil-cpp                20211102.0           h6b3803e_1    conda-forge
absl-py                   1.2.0                    pypi_0    pypi
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py310hf8d0d8f_2    conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3                    pypi_0    pypi
attrs                     22.1.0             pyh71513ae_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h1c322ee_7    conda-forge
brotli-bin                1.0.9                h1c322ee_7    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.18.1               h3422bc3_0    conda-forge
ca-certificates           2022.6.15            h4653dfc_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.6.15                pypi_0    pypi
cffi                      1.15.1          py310he00a5c5_0    conda-forge
charset-normalizer        2.1.0                    pypi_0    pypi
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
debugpy                   1.6.0           py310h1105856_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.5.1                  pypi_0    pypi
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
etils                     0.6.0                    pypi_0    pypi
executing                 0.9.1              pyhd8ed1ab_0    conda-forge
flatbuffers               1.12                     pypi_0    pypi
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
fonttools                 4.34.4          py310h02f21da_0    conda-forge
freetype                  2.10.4               h17b34a0_1    conda-forge
gast                      0.4.0                    pypi_0    pypi
giflib                    5.2.1                h27ca646_2    conda-forge
google-auth               2.9.1                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
googleapis-common-protos  1.56.4                   pypi_0    pypi
grpc-cpp                  1.48.0               hd7338e0_0    conda-forge
grpcio                    1.48.0          py310h00f59f9_0    conda-forge
h5py                      3.6.0           nompi_py310hb8bbf05_100    conda-forge
hdf5                      1.12.1          nompi_hd9dbc9e_104    conda-forge
idna                      3.3                      pypi_0    pypi
importlib-metadata        4.11.4          py310hbe9552e_0    conda-forge
importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.15.1             pyh736e0ef_0    conda-forge
ipython                   8.4.0           py310hbe9552e_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.7.1              pyhd8ed1ab_0    conda-forge
jedi                      0.18.1          py310hbe9552e_1    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   he4db4b2_2    conda-forge
jsonschema                4.9.0              pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0           py310hbe9552e_7    conda-forge
jupyter_client            7.3.4              pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1          py310hbe9552e_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.1              pyhd8ed1ab_0    conda-forge
keras                     2.9.0                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.4.4           py310hd23d0e8_0    conda-forge
krb5                      1.19.3               he492e65_0    conda-forge
lcms2                     2.12                 had6a04f_0    conda-forge
lerc                      4.0.0                h9a09cb3_0    conda-forge
libblas                   3.9.0           15_osxarm64_openblas    conda-forge
libbrotlicommon           1.0.9                h1c322ee_7    conda-forge
libbrotlidec              1.0.9                h1c322ee_7    conda-forge
libbrotlienc              1.0.9                h1c322ee_7    conda-forge
libcblas                  3.9.0           15_osxarm64_openblas    conda-forge
libclang                  14.0.6                   pypi_0    pypi
libcurl                   7.83.1               h7965298_0    conda-forge
libcxx                    14.0.6               h04bba0f_0    conda-forge
libdeflate                1.12                 he4db4b2_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0.dev0      11_0_1_hf114ba7_23    conda-forge
libgfortran5              11.0.1.dev0         hf114ba7_23    conda-forge
liblapack                 3.9.0           15_osxarm64_openblas    conda-forge
libnghttp2                1.47.0               hf30690b_0    conda-forge
libopenblas               0.3.20          openmp_h130de29_1    conda-forge
libpng                    1.6.37               h2c9beb0_3    conda-forge
libprotobuf               3.20.1               h332123e_0    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libssh2                   1.10.0               h7a5bd25_2    conda-forge
libtiff                   4.4.0                h57e8767_2    conda-forge
libwebp                   1.2.3                h1e26fe3_1    conda-forge
libwebp-base              1.2.3                he4db4b2_2    conda-forge
libxcb                    1.13              h9b22ae9_1004    conda-forge
libzlib                   1.2.12               ha287fd2_2    conda-forge
llvm-openmp               14.0.4               hd125106_0    conda-forge
lz4-c                     1.9.3                hbdafb3b_1    conda-forge
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1           py310hf8d0d8f_1    conda-forge
matplotlib                3.5.2           py310hb6292c7_1    conda-forge
matplotlib-base           3.5.2           py310hbeb1b0d_1    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py310he2143c4_1005    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclient                  0.5.13             pyhd8ed1ab_0    conda-forge
nbconvert                 6.4.5           py310hbe9552e_0    conda-forge
nbformat                  5.4.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
nest-asyncio              1.5.5              pyhd8ed1ab_0    conda-forge
notebook                  6.4.12             pyha770c72_0    conda-forge
numpy                     1.22.4          py310h0a343b5_0    conda-forge
oauthlib                  3.2.0                    pypi_0    pypi
openjpeg                  2.4.0                h062765e_1    conda-forge
openssl                   3.0.5                h7aea29f_1    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.3           py310ha6a5cd6_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0           py310hc9df86f_0    conda-forge
pip                       22.2.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
prometheus_client         0.14.1             pyhd8ed1ab_0    conda-forge
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.30             pyha770c72_0    conda-forge
prompt_toolkit            3.0.30               hd8ed1ab_0    conda-forge
protobuf                  3.19.4                   pypi_0    pypi
psutil                    5.9.1           py310h02f21da_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.12.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1          py310hf8d0d8f_1    conda-forge
python                    3.10.5          h4eee789_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.1             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyzmq                     23.2.0          py310hede2015_0    conda-forge
re2                       2022.06.01           h9a09cb3_0    conda-forge
readline                  8.1.2                h46ed386_0    conda-forge
requests                  2.28.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scikit-learn              1.1.1           py310h16bc539_0    conda-forge
scipy                     1.9.0           py310hdb41229_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                63.3.0          py310hbe9552e_0    conda-forge
six                       1.15.0                   pypi_0    pypi
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlite                    3.39.2               h40dfcc0_0    conda-forge
stack_data                0.3.0              pyhd8ed1ab_0    conda-forge
tensorboard               2.9.1                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow-datasets       4.6.0                    pypi_0    pypi
tensorflow-deps           2.9.0                         0    apple
tensorflow-estimator      2.9.0                    pypi_0    pypi
tensorflow-macos          2.9.2                    pypi_0    pypi
tensorflow-metadata       1.9.0                    pypi_0    pypi
tensorflow-metal          0.5.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.15.0          py310hbe9552e_0    conda-forge
testpath                  0.6.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
toml                      0.10.2                   pypi_0    pypi
tornado                   6.2             py310h02f21da_0    conda-forge
tqdm                      4.64.0                   pypi_0    pypi
traitlets                 5.3.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.3.0                    pypi_0    pypi
tzdata                    2022a                h191b570_0    conda-forge
unicodedata2              14.0.0          py310hf8d0d8f_1    conda-forge
urllib3                   1.26.11                  pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  2.2.1                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.6.1              pyha770c72_0    conda-forge
wrapt                     1.14.1                   pypi_0    pypi
xorg-libxau               1.0.9                h27ca646_0    conda-forge
xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
zeromq                    4.3.4                hbdafb3b_1    conda-forge
zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               ha287fd2_2    conda-forge
zstd                      1.5.2                hd705a24_2    conda-forge
